{% set name = "backports.unittest_mock" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backports.unittest_mock-{{ version }}.tar.gz
  sha256: b693b7dee5db7e13d0b31ddc84768cc672ac9a2b03aad3c83b0f28d32ef53e6f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm >=1.15.0
  run:
    - python >=3.6

test:
  imports:
    - backports
    - backports.unittest_mock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/backports.unittest_mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: backports.unittest_mock

extra:
  recipe-maintainers:
    - corburn
