{% set version = "1.5" %}
{% set sha256 = "eff58e53de8fdeb27a1c87a9d57e7b91d15d1bc3854e85344b1a2e69f31ecda7" %}

package:
  name: backports.unittest_mock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/backports.unittest_mock/backports.unittest_mock-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
    - backports
  run:
    - python
    - mock  # [py27]
    - backports

test:
  imports:
    - backports.unittest_mock

about:
  home: https://github.com/jaraco/backports.unittest_mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: backports.unittest_mock

extra:
  recipe-maintainers:
    - corburn
