{% set name = "backports.unittest_mock" %}
{% set version = "1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backports.unittest_mock-{{ version }}.tar.gz
  sha256: eff58e53de8fdeb27a1c87a9d57e7b91d15d1bc3854e85344b1a2e69f31ecda7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm >=1.15.0
  run:
    - python >=3.6

test:
  imports:
    - backports
    - backports.unittest_mock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/backports.unittest_mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: backports.unittest_mock

extra:
  recipe-maintainers:
    - corburn
