travis:
  secure:
    BINSTAR_TOKEN: KpI9YWrSj5B/QBu5WH6O1DzV6Qgl9C8hRHeODlKhKMU7rwrEMvHpNmLuZZhJ53aNkcPhKhBmpZ9oNetGTwnTTvPdj+XXtiKsFYEb5OcNx2497wdcAmJ8KAr0ROQ5RbeI0rMeu6gyDRPFZ1xb0qOUqgNgFmJOQk/mgJeQHOD82hTOl/02295oSth0jjfmcGG2PyTHy8Px8Yao4n2Yb/lFvw3xgGnSZxFp9fvAuHWgvS3QJMc2rqxPmim6qSQuqFj7FvSKLCst77KCvZ0XBWEeAiuGjmPwjSDETgPiDDb0WAnAFQf8dDIcPuJkkVSk0U8sz9WrgzJRDJNvNJYo9VkTT9l2C3glHmXDp3X0ekJghgIYSQGWCP7z80BPys90U3lfiRttu7dkd5Q9vP2BDf3X6z9ZgGeNxXqMyXWKSD5JPdTEjGK0fHCgjCurQIVrUlT7wyuJm5mJ/JcjlNiz/okZolr14s95sBszYWJKPC0K83blWjE64M1L1g7phmDPNCMYuRhH807JchctACFltuOMX5XzNohSLISZmBwsUg4faCBx51HtC3tftAs9v+/YqB3VYMQ3ewjmAnKpf016PiN2CVVP5kFdPPlkE/THgdj0/n0J+xJvUW+PX9WRmXTUqTdieI5nre8fkCBzjLZPtRVfu0u/i4rWBsCTXuA59WRDY/k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
